### ISSUE TITLE
Error running docker build

### ISSUE THREAD

**Issue by taiblokman** [redis-developer/redis-datasets#12]
Hi, I'm getting these errors when i run "docker build -t redis-fraud:latest ."
- Docker desktop 4.9.1
- Python 3.8
- Mac OS 12.3.1 (Intel) 

>ERROR [6/6] RUN pip3 install -r /app/requirements.txt                                                       2.1s
[6/6] RUN pip3 install -r /app/requirements.txt:
#9 1.009 Collecting git+https://github.com/RedisGears/redisgears-py.git (from -r /app/requirements.txt (line 6))
#9 1.010   Cloning https://github.com/RedisGears/redisgears-py.git to /tmp/pip-xrft9j0w-build
#9 2.006     Complete output from command python setup.py egg_info:
#9 2.006     Traceback (most recent call last):
#9 2.006       File "<string>", line 1, in <module>
#9 2.006       File "/usr/lib/python3.6/tokenize.py", line 452, in open
#9 2.006         buffer = _builtin_open(filename, 'rb')
#9 2.006     FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-xrft9j0w-build/setup.py'
#9 2.006
#9 2.006     ----------------------------------------
#9 2.007 Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-xrft9j0w-build/
------
executor failed running [/bin/sh -c pip3 install -r /app/requirements.txt]: exit code: 1

**Comment by salimdason** [comment]
Edit your Dockerfile's RUN commands to upgrade pip

RUN apt-get update -y && \
    apt-get install -y python3.7 python3-pip build-essential git && \
    pip3 install --upgrade pip

and 

RUN pip3 install -r /app/requirements.txt


This should solve your problem
